
services:
  app:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - material_data_prod:/usr/src/app/data
      - material_uploads_prod:/usr/src/app/uploads
    environment:
      NODE_ENV: production
      PORT: 8081
    env_file:
      - .env
    restart: always
    command: ["npm", "start"]

volumes:
  material_data_prod:
  material_uploads_prod:
